from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form
from sqlalchemy.orm import Session
from database import get_db
import models
from schemas import UploadBillResponse
from datetime import date
from typing import Optional

# Import the unified Student 2 + Student 3 processing pipeline
from services import (
    run_complete_student2_pipeline,
    generate_tips_for_manual_entry,
    AIServiceUnavailableError,
)

router = APIRouter()
REGION_MAP = {
    "01": "Chennai North",
    "02": "Chennai South",
    "03": "Coimbatore",
    "04": "Madurai",
    "05": "Thanjavur",
    "06": "Trichy",
    "07": "Salem",
    "08": "Tirunelveli",
    "09": "Vellore",
    "10": "Erode"
}

def calculate_amount_due(units_consumed: float, tariff_category: str):
    tariff = tariff_category.strip().lower()

    if tariff == "domestic":
        if units_consumed <= 200:
            amount_due = 0
        elif units_consumed <= 400:
            amount_due = (units_consumed - 200) * 4.70
        elif units_consumed <= 500:
            amount_due = (200 * 4.70) + ((units_consumed - 400) * 6.30)
        elif units_consumed <= 600:
            amount_due = (200 * 4.70) + (100 * 6.30) + ((units_consumed - 500) * 8.40)
        elif units_consumed <= 800:
            amount_due = (200 * 4.70) + (100 * 6.30) + (100 * 8.40) + ((units_consumed - 600) * 9.45)
        elif units_consumed <= 1000:
            amount_due = (
                (200 * 4.70)
                + (100 * 6.30)
                + (100 * 8.40)
                + (200 * 9.45)
                + ((units_consumed - 800) * 10.50)
            )
        else:
            amount_due = (
                (200 * 4.70)
                + (100 * 6.30)
                + (100 * 8.40)
                + (200 * 9.45)
                + (200 * 10.50)
                + ((units_consumed - 1000) * 11.55)
            )

    elif tariff == "commercial":
        amount_due = units_consumed * 8.0

    else:
        raise HTTPException(
            status_code=400,
            detail="Invalid tariff category."
        )

    return round(amount_due, 2)
    

@router.post("/upload-bill", response_model=UploadBillResponse)
async def upload_bill(
    consumer_number: Optional[str] = Form(None), 
    bill_month: Optional[date] = Form(None),
    tariff_category: Optional[str] = Form(None),
    units_consumed: Optional[float] = Form(None),
    file: Optional[UploadFile] = File(None),
    db: Session = Depends(get_db)
):
    try:
        ai_summary = "Manual Entry — insufficient data for AI analysis."
        saving_tips = ["Conserve appliance usage where possible."]

        if file:
            pipeline_results = await run_complete_student2_pipeline(file)

            # Map values extracted by Student 2
            consumer_number = pipeline_results["consumer_number"]
            bill_month = pipeline_results["bill_month"]
            units_consumed = pipeline_results["units_consumed"]
            tariff_category = pipeline_results["tariff_category"]

            # Map values generated by Student 3
            ai_summary = pipeline_results["ai_summary"]
            saving_tips = pipeline_results["saving_tips"]

        elif units_consumed is not None and tariff_category is not None and consumer_number is not None:
            manual_results = await generate_tips_for_manual_entry(
                units_consumed=units_consumed,
                tariff_category=tariff_category
            )
            ai_summary = manual_results["ai_summary"]
            saving_tips = manual_results["saving_tips"]

        # Validate that we have all core variables needed
        if any(v is None for v in [consumer_number, bill_month, tariff_category, units_consumed]):
            raise HTTPException(
                status_code=400,
                detail="Missing required bill fields. Please provide a valid file or complete all form fields including consumer number."
            )
        # Validate consumer number
        consumer_number = consumer_number.strip()
        if not consumer_number.isdigit():
            raise HTTPException(status_code=400,detail="Consumer number must contain only digits.")

        if len(consumer_number) not in (10, 12):
            raise HTTPException(status_code=400, detail="Consumer number must be 10 or 12 digits.")
        region_code=consumer_number[:2]
        region_name=REGION_MAP.get(region_code,"UNKNOWN")
        # Look up or create the User mapped to this consumer number
        user = db.query(models.User).filter(models.User.consumer_number == consumer_number).first()
        
        if not user:
            email_slug = "".join(e for e in consumer_number if e.isalnum())
            # FIX: Do not pass an explicit 'id' attribute here. 
            # Let the database handle auto-increment sequences cleanly.
            user = models.User(consumer_number=consumer_number,name=f"User_{consumer_number}",email=f"user_{email_slug}@example.com")
            db.add(user)
            try:
                db.commit()
                db.refresh(user)
            except Exception:
                db.rollback()
                # Safe fallback if concurrent requests attempt creation simultaneously
                user = db.query(models.User).filter(models.User.name == user_name).first()
    
        amount_due = calculate_amount_due(units_consumed=units_consumed, tariff_category=tariff_category)
        
        # Save bill records to the database
        new_bill = models.Bill(consumer_number=user.consumer_number,region=region_name,bill_month=bill_month,tariff_category=tariff_category,units_consumed=units_consumed,amount_due=amount_due)
        db.add(new_bill)
        db.commit()
        db.refresh(new_bill)

        # Save the analysis data
        new_analysis = models.Analysis(
            bill_id=new_bill.id,
            ai_summary=ai_summary,
            saving_tips=saving_tips
        )
        db.add(new_analysis)
        db.commit()
        db.refresh(new_analysis)

        return UploadBillResponse(
    consumer_number=new_bill.consumer_number,
    region=new_bill.region,
    tariff_category=new_bill.tariff_category,
    units_consumed=new_bill.units_consumed,
    amount_due=new_bill.amount_due,
    bill_month=str(new_bill.bill_month),
    ai_summary=new_analysis.ai_summary,
    saving_tips=new_analysis.saving_tips
)

    except HTTPException:
        raise
    except AIServiceUnavailableError as e:
        db.rollback()
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))
