from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form
from sqlalchemy.orm import Session
from database import get_db
import models
from schemas import UploadBillResponse
from datetime import date
from typing import Optional

# Import the unified Student 2 + Student 3 processing pipeline
from services import (
    run_complete_student2_pipeline,
    generate_tips_for_manual_entry,
    AIServiceUnavailableError,
)

router = APIRouter()

@router.post("/upload-bill", response_model=UploadBillResponse)
async def upload_bill(
    user_id: int = Form(...),
    consumer_number: Optional[str] = Form(None),
    bill_month: Optional[date] = Form(None),
    tariff_category: Optional[str] = Form(None),
    units_consumed: Optional[float] = Form(None),
    file: Optional[UploadFile] = File(None),
    db: Session = Depends(get_db)
):
    try:
        # 1. Check if user exists; if not, create a fallback profile
        user = db.query(models.User).filter(models.User.id == user_id).first()
        if not user:
            user = models.User(
                id=user_id,
                name=f"User{user_id}",
                email=f"user{user_id}@example.com"
            )
            db.add(user)
            db.commit()
            db.refresh(user)

        # Default fallback placeholders — only used if neither a file nor enough
        # manual data is available to call the AI at all
        ai_summary = "Manual Entry — insufficient data for AI analysis."
        saving_tips = ["Conserve appliance usage where possible."]

        # 2. If a bill file is uploaded, run the unified extraction & tips pipeline
        if file:
            pipeline_results = await run_complete_student2_pipeline(file)

            # Map values extracted by Student 2
            consumer_number = pipeline_results["consumer_number"]
            bill_month = pipeline_results["bill_month"]
            units_consumed = pipeline_results["units_consumed"]
            tariff_category = pipeline_results["tariff_category"]

            # Map values generated by Student 3
            ai_summary = pipeline_results["ai_summary"]
            saving_tips = pipeline_results["saving_tips"]

        # 2b. No file, but the user typed in enough info manually —
        # still get real, tailored AI tips instead of a static placeholder
        elif units_consumed is not None and tariff_category is not None:
            manual_results = await generate_tips_for_manual_entry(
                units_consumed=units_consumed,
                tariff_category=tariff_category
            )
            ai_summary = manual_results["ai_summary"]
            saving_tips = manual_results["saving_tips"]

        # 3. Validate that we have all mandatory fields (either from Form or AI)
        if any(v is None for v in [consumer_number, bill_month, tariff_category, units_consumed]):
            raise HTTPException(
                status_code=400,
                detail="Missing required bill fields. Please provide a valid file or complete all form fields."
            )

        # 4. Calculate amount due based on the tariff tier rules
        if tariff_category.lower() == "domestic":
            amount_due = units_consumed * 7
        elif tariff_category.lower() == "commercial":
            amount_due = units_consumed * 8
        else:
            amount_due = units_consumed * 9

        # 5. Save bill records to the database
        new_bill = models.Bill(
            user_id=user.id,
            consumer_number=consumer_number,
            bill_month=bill_month,
            tariff_category=tariff_category,
            units_consumed=units_consumed,
            amount_due=amount_due
        )
        db.add(new_bill)
        db.commit()
        db.refresh(new_bill)

        # 6. Save the analysis data (Summary + Saving Tips array) linked to the bill
        new_analysis = models.Analysis(
            bill_id=new_bill.id,
            ai_summary=ai_summary,
            saving_tips=saving_tips
        )
        db.add(new_analysis)
        db.commit()
        db.refresh(new_analysis)

        # 7. Return the finalized response back to the client
        return UploadBillResponse(
            bill_id=new_bill.id,
            tariff_category=new_bill.tariff_category,
            units_consumed=new_bill.units_consumed,
            amount_due=new_bill.amount_due,
            bill_month=str(new_bill.bill_month),
            ai_summary=new_analysis.ai_summary,
            saving_tips=new_analysis.saving_tips  # Returns the live JSON array directly
        )

    except HTTPException:
        raise
    except AIServiceUnavailableError as e:
        db.rollback()
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))
